name: windfiresteel's blog
description: A blog and collection of short stories
author: windfiresteel
theme: jekyll-theme-hacker

sidebar: true
sidebar-about-description: is this working?
github_user: windfiresteel
rss: true
twitter: windfiresteel
youtube: windfiresteel
