theme: jekyll-theme-hacker
title: Blog and Short story archive
name: Jon's Site
description: I will eventually repost all of my old short stories here and occaisionally blog
email: windfiresteel1@gmail.com
github: windfiresteel
rss: ok # just type anything here
twitter: windfiresteel 
youtube: user/windfiresteel

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
