name: windfiresteel's blog
description: A blog and collection of short stories
baseurl: windfiresteel.github.io/blog
author: Ace
theme: jekyll-theme-hacker

github_user: windfiresteel
twitter: windfiresteel
youtube: windfiresteel
deviantart: khatru
tumblr: windfiresteel

rss: true

markdown: kramdown
