name: windfiresteel's blog
description: A blog and collection of short stories
author: windfiresteel
theme: jekyll-theme-hacker

github_user: windfiresteel
rss: ok
twitter: windfiresteel
youtube: user/<windfiresteel>
