name: windfiresteel's blog
description: A blog and collection of short stories
theme: jekyll-theme-hacker

social-network-links:
  github: windfiresteel
  rss: true
  twitter: windfiresteel
  youtube: user/<windfiresteel>
