name: windfiresteel's blog
description: A blog and collection of short stories
theme: jekyll-theme-hacker

footer-links:
  github: windfiresteel
  rss: ok
  twitter: windfiresteel
  youtube: user/<windfiresteel>

permalink: /:title/

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
